apps/galeria/urls.py
from django.urls import path
from apps.galeria import views

app_name = 'apps.galeria'

urlpatterns = [
    path('', views.index, name='index'),
    path('imagem/<int:foto_id>', views.imagem, name='imagem'),
    path('buscar', views.buscar, name='buscar'),
    path('nova_imagem', views.nova_imagem, name='nova_imagem'),
    path('editar_imagem/<int:foto_id>', views.editar_imagem, name='editar_imagem'),
    path('deletar_imagem/<int:foto_id>', views.deletar_imagem, name='deletar_imagem'),
    path('filtro_imagem/<str:armadura>', views.filtro_imagem, name='filtro_imagem'),
]

galeria/urls.py
from django.urls import path
from . import views

app_name = 'galeria'

urlpatterns = [
    path('', views.index, name='index'),
    path('imagem/<int:foto_id>', views.imagem, name='imagem'),
    path('buscar', views.buscar, name='buscar')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.galeria.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/galeria/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Cavaleiro(models.Model):

    OPCOES_CATEGORIAS = [
        ('BRONZE', 'Bronze'),
        ('OURO', 'Ouro'),
        ('PRATA', 'Prata'),
    ]
 
    usuario = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name='user',
    )
    
    nome = models.CharField(max_length=100, blank=False, null=False)
    constelacao = models.CharField(max_length=100, blank=False, null=False)
    armadura = models.CharField(max_length=100, choices=OPCOES_CATEGORIAS, default='')
    historia = models.TextField()
    imagem = models.ImageField(blank=True, upload_to='galeria/%Y%m')

    def __str__(self) -> str:
        return f'{self.nome} - {self.constelacao}'

apps/galeria/forms.py
from django import forms
from apps.galeria.models import Cavaleiro

class FotografiaForms(forms.ModelForm):
    class Meta:
        model = Cavaleiro
        exclude = ['usuario',]
        labels = {
            'constelacao': 'Constelação',
            'historia': 'História',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'constelacao': forms.TextInput(attrs={'class': 'form-control'}),
            'armadura': forms.Select(attrs={'class': 'form-control'}),
            'historia': forms.Textarea(attrs={'class': 'form-control'}),
            'imagem': forms.FileInput(attrs={'class': 'form-control'}),
        }

apps/galeria/views.py
from django.shortcuts import get_object_or_404, redirect, render
from apps.galeria.forms import FotografiaForms
from apps.galeria.models import Cavaleiro
from django.contrib import messages

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        messages.error(request,'Usuário não logado!')
        return redirect('apps.usuarios:login')
    cavaleiro = Cavaleiro.objects.all()
    context = {
        'cavaleiros': cavaleiro
    }
    return render(request, 'galeria/index.html', context)

def imagem(request, foto_id):
    cavaleiro = get_object_or_404(Cavaleiro, pk=foto_id)
    context = {
        'cavaleiro': cavaleiro
    }
    return render(request, 'galeria/imagem.html', context)

def buscar(request):
    if not request.user.is_authenticated:
        messages.error(request,'Usuário não logado!')
        return redirect('apps.usuarios:login')
    cavaleiro = Cavaleiro.objects.order_by('-nome')

    if 'buscar' in request.GET:
        nome_a_buscar = request.GET['buscar']
        if nome_a_buscar:
            cavaleiro = Cavaleiro.objects.filter(nome__icontains=nome_a_buscar)
        context = {
            'cavaleiros': cavaleiro
        }
    return render(request, 'galeria/buscar.html', context)

def nova_imagem(request):
    if not request.user.is_authenticated:
        messages.error(request,'Usuário não logado!')
        return redirect('apps.usuarios:login')
    
    form = FotografiaForms
    if request.method == 'POST':
        form = FotografiaForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Nova fotografia cadastrada')
            return redirect('apps.galeria:index')
    context = {
        'form': form,
    }
    return render(request, 'galeria/nova_imagem.html', context)

def editar_imagem(request, foto_id):
    fotografia = Cavaleiro.objects.get(id=foto_id)
    form = FotografiaForms(instance=fotografia)
    if request.method == 'POST':
        form = FotografiaForms(request.POST, request.FILES, instance=fotografia)
        messages.success(request, 'Fotografia editada.')
        return redirect('apps.galeria:index')
    context = {
        'form': form,
        'foto_id': foto_id,
    }
    return render(request, 'galeria/editar_imagem.html', context)

def deletar_imagem(request, foto_id):
    fotografia = Cavaleiro.objects.get(id=foto_id)
    fotografia.delete()
    messages.success(request, 'Fotografia deletada.')
    return redirect('apps.galeria:index')

def filtro_imagem(request, armadura):
    cavaleiros = Cavaleiro.objects.order_by('armadura').filter(armadura=armadura)
    context = {
        'cavaleiros': cavaleiros
    }
    return render(request, 'galeria/index.html', context)

galeria/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Cavaleiro
from django.contrib import messages

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        messages.error(request,'Usuário não logado!')
        return redirect('usuarios:login')
    cavaleiro = Cavaleiro.objects.all()
    context = {
        'cavaleiros': cavaleiro
    }
    return render(request, 'galeria/index.html', context)

def imagem(request, foto_id):
    cavaleiro = get_object_or_404(Cavaleiro, pk=foto_id)
    context = {
        'cavaleiro': cavaleiro
    }
    return render(request, 'galeria/imagem.html', context)

def buscar(request):
    if not request.user.is_authenticated:
        messages.error(request,'Usuário não logado!')
        return redirect('usuarios:login')
    cavaleiro = Cavaleiro.objects.order_by('-nome')

    if 'buscar' in request.GET:
        nome_a_buscar = request.GET['buscar']
        if nome_a_buscar:
            cavaleiro = Cavaleiro.objects.filter(nome__icontains=nome_a_buscar)
        context = {
            'cavaleiros': cavaleiro
        }
    return render(request, 'galeria/buscar.html', context)

galeria/templates/galeria/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pagina principal{% endblock %}

{% block content %}

            <section class="conteudo">
                <section class="banner">
                    <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
                    <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
                </section>
                <section class="tags">
                    <p class="tags__titulo">Busque por tags:</p>
                    <ul class="tags__lista">
                        <li class="tags__tag">Nebulosa</li>
                        <li class="tags__tag">Estrela</li>
                        <li class="tags__tag">Galáxia</li>
                        <li class="tags__tag">Planeta</li>
                    </ul>
                </section>
                <section class="galeria">
                    <div class="cards">
                        <h2 class="cards__titulo">Navegue pela galeria</h2>
                        <ul class="cards__lista">
                            {% if cavaleiros %}
                                {% for cavaleiro in cavaleiros %}
                                    <li class="card">
                                        </br>
                                        <a href="{% url 'galeria:imagem' cavaleiro.id %}">
                                            <img class="card__imagem" src="{{cavaleiro.imagem.url}}" alt="{{cavaleiro.nome}}">
                                        </a>
                                        <span class="card__tag">{{ cavaleiro.constelacao }}</span>
                                        <div class="card__info">
                                            <p class="card__titulo">{{ cavaleiro.nome }}</p>
                                            <div class="card__texto">
                                                <p class="card__descricao">{{ cavaleiro.historia }}</p>
                                                </br>
                                                <span>
                                                    <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                                </span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </section>
            </section>
        </main>
    </div>
{% endblock %}