apps/usuarios/urls.py
from django.urls import path
from apps.usuarios import views

app_name = 'apps.usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.galeria.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
]

apps/usuarios/models.py
from django.db import models

# Create your models here.

apps/usuarios/forms.py
from typing import Any
from django import forms

class LoginForms(forms.Form):
    nome_login = forms.CharField(label='Nome de login', required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Ex.: João Silva',
        }
    ))
    
    senha = forms.CharField(label='Senha', required=True, max_length=50, widget=forms.PasswordInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Digite sua senha',
        }
    ))

class CadastroForms(forms.Form):
    nome_cadastro = forms.CharField(label='Nome de cadastro', required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Ex.: João Silva',
        }
    ))

    email = forms.EmailField(label='Email', required=True, max_length=50, widget=forms.EmailInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Ex.: nome@email.com',
        }
    ))

    primeira_senha = forms.CharField(label='Senha', required=True, max_length=50, widget=forms.PasswordInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Digite sua senha',
        }
    ))

    segunda_senha = forms.CharField(label='Confirme sua Senha', required=True, max_length=50, widget=forms.PasswordInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Digite sua senha novamente',
        }
    ))

    def clean_nome_cadastro(self):
        nome = self.cleaned_data.get('nome_cadastro')
        if nome:
            nome = nome.strip()
            if ' ' in nome:
                raise forms.ValidationError('Não é possível incerir espaços dentro do compo (nome cadastro).')
            else:
                return nome

    def clean_segunda_senha(self):
        primeira_senha = self.cleaned_data.get('primeira_senha')
        segunda_senha = self.cleaned_data.get('segunda_senha')
        if primeira_senha and segunda_senha:
            if primeira_senha != segunda_senha:
                raise forms.ValidationError('As senhas não são iguais.')
            else:
                return segunda_senha

apps/usuarios/views.py
from django.shortcuts import redirect, render
from apps.usuarios.forms import LoginForms, CadastroForms
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages

# Create your views here.
def login(request):
    template_name = 'usuarios/login.html'
    form = LoginForms()

    if request.method == 'POST':
        form = LoginForms(request.POST)
        if form.is_valid():
            nome = form['nome_login'].value()
            senha = form['senha'].value()

            usuario = auth.authenticate(
                username = nome,
                password = senha
            )

            if usuario is not None:
                auth.login(request, usuario)
                messages.success(request, f'Usuário {nome} logado com sucesso')
                return redirect('apps.galeria:index')
                
            else:
                messages.error(request, f'Erro ao efetua login.')
                return redirect('apps.galeria:index')
    
    context = {
        'form': form,
    }
    return render(request, template_name, context)

def cadastro(request):
    template_name = 'usuarios/cadastro.html'
    form = CadastroForms()

    if request.method == 'POST':
        form = CadastroForms(request.POST)
        
        if form.is_valid():
            nome_casdatro = form['nome_cadastro'].value()
            email = form['email'].value()
            senha = form['primeira_senha'].value()

            if User.objects.filter(username=nome_casdatro).exists():
                messages.error(request, 'Usuário já existente.')
                return redirect(template_name)

            usuario = User.objects.create_user(
                username = nome_casdatro,
                email = email,
                password = senha,
            )
            usuario.save()
            messages.success(request, 'Cadastro efetuado com sucesso.')
            return redirect('apps.usuarios:login')
            
    context = {
        'form': form,
    }
    return render(request, template_name, context)

def logout(request):
    auth.logout(request)
    messages.success(request, 'Logout do usuário efetuado com sucesso.')
    return redirect('apps.usuarios:login')

usuarios/views.py
from django.shortcuts import redirect, render
from usuarios.forms import LoginForms, CadastroForms
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages

# Create your views here.
def login(request):
    template_name = 'usuarios/login.html'
    form = LoginForms()

    if request.method == 'POST':
        form = LoginForms(request.POST)
        if form.is_valid():
            nome = form['nome_login'].value()
            senha = form['senha'].value()

            usuario = auth.authenticate(
                username = nome,
                password = senha
            )

            if usuario is not None:
                auth.login(request, usuario)
                messages.success(request, f'Usuário {nome} logado com sucesso')
                return redirect('galeria:index')
                
            else:
                messages.error(request, f'Erro ao efetua login.')
                return redirect('galeria:index')
    
    context = {
        'form': form,
    }
    return render(request, template_name, context)

def cadastro(request):
    template_name = 'usuarios/cadastro.html'
    form = CadastroForms()

    if request.method == 'POST':
        form = CadastroForms(request.POST)
        
        if form.is_valid():
            nome_casdatro = form['nome_cadastro'].value()
            email = form['email'].value()
            senha = form['primeira_senha'].value()

            if User.objects.filter(username=nome_casdatro).exists():
                messages.error(request, 'Usuário já existente.')
                return redirect(template_name)

            usuario = User.objects.create_user(
                username = nome_casdatro,
                email = email,
                password = senha,
            )
            usuario.save()
            messages.success(request, 'Cadastro efetuado com sucesso.')
            return redirect('usuarios:login')
            
    context = {
        'form': form,
    }
    return render(request, template_name, context)

def logout(request):
    auth.logout(request)
    messages.success(request, 'Logout do usuário efetuado com sucesso.')
    return redirect('usuarios:login')

usuarios/templates/usuarios/cadastro.html
{% extends "base.html" %}
{% load static %}

<title>{% block title %}Pagina de cadastro{% endblock %}</title>

{% block content %}
                        <head>
                            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
                        </head>
                        <section class="galeria" style="margin-left: 5em">
                            <form action="{% url 'usuarios:cadastro' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {% for field in form.visible_fields %}
                                        <div class="col-12 col-lg-12" style="margin-bottom: 10px">
                                            <label for="{{ field.id_for_label }}" style="color:#D9D9D9; margin-bottom: 10px">{{ field.label }}</label>
                                            {{ field }}
                                        </div>
                                        {% include "partials/_alertas.html" %}
                                    {% endfor %}
                                    <div class="col-12 col-lg-12" style="margin-bottom: 10px">
                                        <button type="submit" class="btn btn-success col-12" style="padding: top 5px">Cadastrar</button>
                                    </div>
                                </div>
                            </form>
                        </section>
                    </div>
                </section>
            </section>
        </main>
    </div>
{% endblock content %}

usuarios/templates/usuarios/login.html
{% extends "base.html" %}
{% load static %}

<title>{% block title %}Pagina de login{% endblock %}</title>

{% block content %}
                        <head>
                            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
                        </head>
                        <section class="galeria" style="margin-left: 5em">
                            <form action="{% url 'usuarios:login' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {% for field in form.visible_fields %}
                                        <div class="col-12 col-lg-12" style="margin-bottom: 10px">
                                            <label for="{{ field.id_for_label }}" style="color:#D9D9D9; margin-bottom: 10px">{{ field.label }}</label>
                                            {{ field }}
                                        </div>
                                        {% include "partials/_alertas.html" %}
                                    {% endfor %}
                                    <div class="col-12 col-lg-12" style="margin-bottom: 10px">
                                        <button type="submit" class="btn btn-success col-12" style="padding: top 5px">Logar</button>
                                    </div>
                                </div>
                            </form>
                        </section>
                    </div>
                </section>
            </section>
        </main>
    </div>
{% endblock content %}